name: ProjectBuild

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ğŸ¥… Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0
    - name: ğŸ¥… Install dependencies
      run: dotnet restore
    - name: ğŸ¥… Build
      run: dotnet build --configuration Release --no-restore
    - name: ğŸ¥… Test
      run: dotnet test --no-restore --verbosity normal
